# Generated by Django 2.2.5 on 2019-09-26 06:42

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190913_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=post.models.image_upload),
        ),
    ]
