# Generated by Django 2.2.5 on 2019-09-29 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='follow',
            new_name='follows',
        ),
    ]
