# Generated by Django 2.2.5 on 2019-09-29 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20190929_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='follows',
        ),
        migrations.AddField(
            model_name='profiles',
            name='followed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profiles',
            name='followed_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
