# Generated by Django 2.2.5 on 2019-09-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190929_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='followed_by',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='followed_to',
        ),
        migrations.AddField(
            model_name='profiles',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='accounts.Profiles'),
        ),
    ]
