# Generated by Django 2.2.5 on 2019-09-29 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190929_0357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='follows',
            new_name='follow_to',
        ),
    ]
