# Generated by Django 2.2.5 on 2019-09-29 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190929_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='follow_to',
            new_name='followed_to',
        ),
    ]
