# Generated by Django 2.2.5 on 2019-10-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190929_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='player_id',
            field=models.IntegerField(null=True),
        ),
    ]
