# Generated by Django 2.2.5 on 2019-10-08 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profiles_player_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='player_id',
        ),
    ]
