# Generated by Django 2.2.5 on 2019-11-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profiles_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
