# Generated by Django 2.2.5 on 2019-11-11 22:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profiles_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.add_avatar),
        ),
    ]
