# Generated by Django 2.2.5 on 2019-09-29 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_auto_20190929_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
